services:
  db:
    image: postgres:16-alpine
    container_name: app_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro


  backend:
    build:
      context: ./backend
    container_name: app_backend
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"


  frontend:
    build:
      context: ./frontend
    container_name: app_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  postgres_data: